@extends('layouts.admin')
@section('title','Kunjungan')
@section('page-title','Data Kunjungan')
@section('content')
<form class="mb-5 rounded-2xl border border-slate-200 bg-white p-4"><div class="grid gap-3 sm:grid-cols-6">@if(auth()->user()->isAdmin())<select name="location_id" class="rounded-xl border border-slate-300 px-4 py-3 text-sm"><option value="">Semua lokasi</option>@foreach($locations as $loc)<option value="{{ $loc->id }}" @selected(request('location_id')==$loc->id)>{{ $loc->name }}</option>@endforeach</select>@endif<input name="search" value="{{ request('search') }}" class="rounded-xl border border-slate-300 px-4 py-3 text-sm sm:col-span-2" placeholder="Nomor, nama, atau perusahaan"><select name="status" class="rounded-xl border border-slate-300 px-4 py-3 text-sm"><option value="">Semua status</option><option value="active" @selected(request('status')==='active')>Belum Survey</option><option value="completed" @selected(request('status')==='completed')>Sudah Survey</option></select><input type="date" name="date" value="{{ request('date') }}" class="min-w-0 rounded-xl border border-slate-300 px-3 py-3 text-sm"><div class="flex gap-2"><button class="flex-1 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Filter</button><a href="{{ route('admin.visits.export', request()->query()) }}" class="flex items-center justify-center rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700">Export Excel</a></div></div></form>
<div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Nomor</th><th class="px-5 py-3">Lokasi</th><th class="px-5 py-3">Tamu</th><th class="px-5 py-3">Tujuan</th><th class="px-5 py-3">Waktu</th><th class="px-5 py-3">Rating</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($visits as $visit)
<tr class="hover:bg-slate-50"><td class="px-5 py-4"><a class="font-bold text-emerald-700" href="{{ route('admin.visits.show',$visit) }}">{{ $visit->visit_number }}</a></td><td class="px-5 py-4">{{ $visit->location?->name ?? '-' }}</td><td class="px-5 py-4"><p class="font-bold">{{ $visit->visitor->name }}</p><p class="text-xs text-slate-500">{{ $visit->visitor->company }}</p></td><td class="px-5 py-4">{{ $visit->employee_name ?: $visit->employee?->name ?: '-' }}<p class="text-xs text-slate-500">{{ $visit->employee?->division?->name ?: '-' }}</p></td><td class="whitespace-nowrap px-5 py-4"><p>{{ $visit->check_in_at->format('d/m/Y H:i') }}</p><p class="text-xs text-slate-500">{{ $visit->surveyed_at?->format('d/m/Y H:i') ?: 'Belum survey' }}</p></td><td class="px-5 py-4">@if($visit->satisfaction_rating)<span class="text-lg tracking-wide text-amber-400">{{ str_repeat('★', $visit->satisfaction_rating) }}</span>@else<span class="text-slate-400">-</span>@endif</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $visit->satisfaction_rating ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-50 text-blue-600' }}">{{ $visit->satisfaction_rating ? 'Sudah Survey' : 'Belum Survey' }}</span></td></tr>
@empty<tr><td colspan="7" class="px-5 py-10 text-center text-slate-500">Data tidak ditemukan.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-5">{{ $visits->links() }}</div>
@endsection
