<?php $__env->startSection('title','Kunjungan'); ?>
<?php $__env->startSection('page-title','Data Kunjungan'); ?>
<?php $__env->startSection('content'); ?>
<form class="mb-5 rounded-2xl border border-slate-200 bg-white p-4"><div class="grid gap-3 sm:grid-cols-6"><?php if(auth()->user()->isAdmin()): ?><select name="location_id" class="rounded-xl border border-slate-300 px-4 py-3 text-sm"><option value="">Semua lokasi</option><?php $__currentLoopData = $locations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $loc): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($loc->id); ?>" <?php if(request('location_id')==$loc->id): echo 'selected'; endif; ?>><?php echo e($loc->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><?php endif; ?><input name="search" value="<?php echo e(request('search')); ?>" class="rounded-xl border border-slate-300 px-4 py-3 text-sm sm:col-span-2" placeholder="Nomor, nama, atau perusahaan"><select name="status" class="rounded-xl border border-slate-300 px-4 py-3 text-sm"><option value="">Semua status</option><option value="active" <?php if(request('status')==='active'): echo 'selected'; endif; ?>>Belum Survey</option><option value="completed" <?php if(request('status')==='completed'): echo 'selected'; endif; ?>>Sudah Survey</option></select><input type="date" name="date" value="<?php echo e(request('date')); ?>" class="min-w-0 rounded-xl border border-slate-300 px-3 py-3 text-sm"><div class="flex gap-2"><button class="flex-1 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Filter</button><a href="<?php echo e(route('admin.visits.export', request()->query())); ?>" class="flex items-center justify-center rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700">Export Excel</a></div></div></form>
<div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Nomor</th><th class="px-5 py-3">Lokasi</th><th class="px-5 py-3">Tamu</th><th class="px-5 py-3">Tujuan</th><th class="px-5 py-3">Waktu</th><th class="px-5 py-3">Rating</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">
<?php $__empty_1 = true; $__currentLoopData = $visits; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $visit): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<tr class="hover:bg-slate-50"><td class="px-5 py-4"><a class="font-bold text-emerald-700" href="<?php echo e(route('admin.visits.show',$visit)); ?>"><?php echo e($visit->visit_number); ?></a></td><td class="px-5 py-4"><?php echo e($visit->location?->name ?? '-'); ?></td><td class="px-5 py-4"><p class="font-bold"><?php echo e($visit->visitor->name); ?></p><p class="text-xs text-slate-500"><?php echo e($visit->visitor->company); ?></p></td><td class="px-5 py-4"><?php echo e($visit->employee_name ?: $visit->employee?->name ?: '-'); ?><p class="text-xs text-slate-500"><?php echo e($visit->employee?->division?->name ?: '-'); ?></p></td><td class="whitespace-nowrap px-5 py-4"><p><?php echo e($visit->check_in_at->format('d/m/Y H:i')); ?></p><p class="text-xs text-slate-500"><?php echo e($visit->surveyed_at?->format('d/m/Y H:i') ?: 'Belum survey'); ?></p></td><td class="px-5 py-4"><?php if($visit->satisfaction_rating): ?><span class="text-lg tracking-wide text-amber-400"><?php echo e(str_repeat('★', $visit->satisfaction_rating)); ?></span><?php else: ?><span class="text-slate-400">-</span><?php endif; ?></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold <?php echo e($visit->satisfaction_rating ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-50 text-blue-600'); ?>"><?php echo e($visit->satisfaction_rating ? 'Sudah Survey' : 'Belum Survey'); ?></span></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="px-5 py-10 text-center text-slate-500">Data tidak ditemukan.</td></tr><?php endif; ?>
</tbody></table></div></div><div class="mt-5"><?php echo e($visits->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\buku-tamu-laravel11\resources\views/admin/visits/index.blade.php ENDPATH**/ ?>