<?php $__env->startSection('title','Lokasi'); ?>
<?php $__env->startSection('page-title','Master Lokasi'); ?>
<?php $__env->startSection('content'); ?>
<div class="mb-5 flex items-center justify-between"><div><p class="text-sm text-slate-500">Kelola Pabrik, HO, cabang, atau lokasi lain.</p></div><a href="<?php echo e(route('admin.locations.create')); ?>" class="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white">+ Tambah Lokasi</a></div>
<div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Lokasi</th><th class="px-5 py-3">Petugas</th><th class="px-5 py-3">Pegawai</th><th class="px-5 py-3">Kunjungan</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">
<?php $__currentLoopData = $locations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $location): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="px-5 py-4"><p class="font-bold"><?php echo e($location->name); ?></p><p class="text-xs text-slate-400"><?php echo e($location->slug); ?></p></td><td class="px-5 py-4"><?php echo e($location->users_count); ?></td><td class="px-5 py-4"><?php echo e($location->employees_count); ?></td><td class="px-5 py-4"><?php echo e($location->visits_count); ?></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold <?php echo e($location->is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'); ?>"><?php echo e($location->is_active ? 'Aktif' : 'Nonaktif'); ?></span></td><td class="px-5 py-4 text-right"><a href="<?php echo e(route('admin.locations.edit',$location)); ?>" class="font-bold text-blue-700">Edit</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</tbody></table></div></div><div class="mt-5"><?php echo e($locations->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\buku-tamu-laravel11\resources\views/admin/locations/index.blade.php ENDPATH**/ ?>