<?php $__env->startSection('title','Petugas'); ?>
<?php $__env->startSection('page-title','Master Petugas'); ?>
<?php $__env->startSection('content'); ?>
<div class="mb-5 flex items-center justify-between"><div><p class="text-sm text-slate-500">Akun petugas dibatasi berdasarkan lokasi.</p></div><a href="<?php echo e(route('admin.users.create')); ?>" class="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white">+ Tambah Petugas</a></div>
<div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Nama</th><th class="px-5 py-3">Email</th><th class="px-5 py-3">Lokasi</th><th class="px-5 py-3">Hak Akses</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">
<?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="px-5 py-4 font-bold"><?php echo e($user->name); ?></td><td class="px-5 py-4"><?php echo e($user->email); ?></td><td class="px-5 py-4"><?php echo e($user->location?->name ?? 'Semua Lokasi'); ?></td><td class="px-5 py-4"><?php echo e($user->isAdmin() ? 'Administrator' : 'Petugas'); ?></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold <?php echo e($user->is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'); ?>"><?php echo e($user->is_active ? 'Aktif' : 'Nonaktif'); ?></span></td><td class="px-5 py-4 text-right"><a href="<?php echo e(route('admin.users.edit',$user)); ?>" class="font-bold text-blue-700">Edit</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</tbody></table></div></div><div class="mt-5"><?php echo e($users->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\buku-tamu-laravel11\resources\views/admin/users/index.blade.php ENDPATH**/ ?>