<?php $__env->startSection('title', 'Dashboard'); ?>
<?php $__env->startSection('page-title', 'Dashboard'); ?>
<?php $__env->startSection('content'); ?>
<div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-slate-500">Data dashboard mengikuti lokasi petugas.</p></div><?php if(auth()->user()->isAdmin()): ?><form><select name="location_id" onchange="this.form.submit()" class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">Semua Lokasi</option><?php $__currentLoopData = $locations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $loc): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($loc->id); ?>" <?php if(request('location_id')==$loc->id): echo 'selected'; endif; ?>><?php echo e($loc->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></form><?php else: ?><div class="rounded-full bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-700"><?php echo e($location?->name ?? '-'); ?></div><?php endif; ?></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
<?php $__currentLoopData = [['Tamu Hari Ini',$stats['today'],'📅'],['Belum Survey',$stats['pending_survey'],'⏳'],['Survey Hari Ini',$stats['surveyed_today'],'✓'],['Rata-rata Rating',$stats['average_rating'] ?: '0','★']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<div class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500"><?php echo e($item[0]); ?></p><p class="mt-3 text-4xl font-black text-slate-900"><?php echo e($item[1]); ?></p></div><div class="grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-xl"><?php echo e($item[2]); ?></div></div></div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</div>
<div class="mt-6 rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 class="font-bold">Kunjungan Terbaru</h3><p class="text-sm text-slate-500">Aktivitas tamu dan hasil survey</p></div><a href="<?php echo e(route('admin.visits.index')); ?>" class="text-sm font-bold text-emerald-700">Lihat semua</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Tamu</th><th class="px-5 py-3">Tujuan</th><th class="px-5 py-3">Masuk</th><th class="px-5 py-3">Survey</th></tr></thead><tbody class="divide-y divide-slate-100">
<?php $__empty_1 = true; $__currentLoopData = $recentVisits; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $visit): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<tr><td class="px-5 py-4"><a href="<?php echo e(route('admin.visits.show',$visit)); ?>" class="font-bold text-slate-900 hover:text-emerald-700"><?php echo e($visit->visitor->name); ?></a><p class="text-xs text-slate-500"><?php echo e($visit->visitor->company); ?></p></td><td class="px-5 py-4"><?php echo e($visit->employee_name ?: $visit->employee?->name ?: '-'); ?><p class="text-xs text-slate-500"><?php echo e($visit->employee?->division?->name ?: '-'); ?></p></td><td class="whitespace-nowrap px-5 py-4"><?php echo e($visit->check_in_at->format('d/m/Y H:i')); ?></td><td class="px-5 py-4"><?php if($visit->satisfaction_rating): ?><span class="text-lg tracking-wide text-amber-400"><?php echo e(str_repeat('★', $visit->satisfaction_rating)); ?></span><?php else: ?><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-600">Belum Survey</span><?php endif; ?></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4" class="px-5 py-10 text-center text-slate-500">Belum ada data kunjungan.</td></tr><?php endif; ?>
</tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\buku-tamu-laravel11\resources\views/admin/dashboard.blade.php ENDPATH**/ ?>